apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rock-music-band
  namespace: 2wesley-argocd  # ArgoCD's namespace
spec:
  project: default
  source:
    repoURL: https://github.com/s5wesley/rock-band-deployment.git
    targetRevision: HEAD
    path: chart  # Path to the Helm chart in the repository
  destination:
    server: https://kubernetes.default.svc  # The Kubernetes API server
    namespace: wesley-app  # The namespace where you want to deploy the application
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
