apiVersion: v1
kind: Service
metadata:
  name: rock-music-band
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30261  # Replace 3589 with a valid port, e.g., 30001
  selector:
    app: rock-music-band
