apiVersion: v1
kind: Service
metadata:
  name: rock-music-band
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Replace 3589 with a valid port, e.g., 30001
  selector:
    app: rock-music-band
